allowBuilds:
  sharp: true
  unrs-resolver: true
  "@clerk/shared": true
  "@prisma/engines": true
  "@prisma/client": true
  prisma: true
  "@sentry/cli": true
  esbuild: true
  core-js: false
  protobufjs: false
  msw: set this to true or false
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - "@clerk/shared"
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - esbuild
  - "@sentry/cli"
